version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - composer install --no-interaction --prefer-dist \
    && ./vendor/bin/parallel-lint src tests \
    && ./vendor/bin/phpunit --verbose --no-coverage \
    && ./vendor/bin/phpcs src tests --standard=psr2 -sp
